version: '3.8'

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: edusync_admin
      POSTGRES_PASSWORD: nexus_secure_pwd
      POSTGRES_DB: edusync_ledger
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  meilisearch:
    image: getmeili/meilisearch:latest
    ports:
      - "7700:7700"
    environment:
      - MEILI_MASTER_KEY=nexus_master_key

volumes:
  mongo_data:
  pg_data:
